test_1: test_1.c
	gcc -g test_1.c -o test_1

test_2: test_2.cpp
	g++ -g test_2.cpp -o test_2

test_3: test_3.cpp
	g++ -g test_3.cpp -o test_3

test_4: test_4.cpp
	g++ -g test_4.cpp -o test_4

test_5: test_5.cpp
	g++ -g test_5.cpp -o test_5

all: test_1 test_2 test_3 test_4 test_5
	 
